[package]
authors = ["Nexus Labs"]
description = "Nexus PoL services contracts"
documentation = "todo"
edition = "2018"
homepage = "todo"
license = "Apache-2.0"
name = "services"
repository = "https://github.com/Nexus-Protocol/pol-contracts"
version = "1.0.0"

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
astroport = "1.0.1"
cosmwasm-std = {version = "0.16.3", features = ["iterator"]}
cw20 = {version = "0.9.1"}
schemars = "0.8.8"
serde = {version = "1.0.133", default-features = false, features = ["derive"]}
